dist: focal

language: python
python:
  - 3.11

cache:
  pip: true
  directories:
    - ${VIRTUAL_ENV}

before_install:
  - curl -sSL https://install.python-poetry.org | python3 -

install:
  - make install

script:
  - make ci

after_script: >
  echo $TRAVIS_BRANCH; echo $TRAVIS_PULL_REQUEST;
  if [[ $TRAVIS_BRANCH == 'main' && $TRAVIS_PULL_REQUEST == 'false' ]]; then

    # Configure Git with Travis CI information
    git config --global user.email "travis@travis-ci.org" ;
    git config --global user.name "travis-ci" ;

    # Delete the current repository
    rm -rf .git ;

    # Clone the destination repository
    git clone https://${GH_TOKEN}@github.com/jacebrowning/template-django-demo temp ;
    mv temp/.git demo_project/.git ;
    rm -rf temp ;

    # Rebuild the repository from the generated files and push to GitHub
    cd demo_project ;
    poetry lock;
    git add --all ;
    git commit -m "Deploy Travis CI build $TRAVIS_BUILD_NUMBER to GitHub" ;
    git push -f https://${GH_TOKEN}@github.com/jacebrowning/template-django-demo main ;

  fi

notifications:
  email:
    on_success: never
    on_failure: change
