version: 2

jobs:
  build:
    working_directory: ~/{{cookiecutter.project_name}}

    docker:
      - image: circleci/python:3.9.9-node-browsers
        environment:
          DATABASE_URL: postgres://circleci:@127.0.0.1:5432/{{cookiecutter.project_name}}_test
          REDIS_URL: redis://127.0.0.1:6379/0
      - image: circleci/postgres:13.5
        environment:
          - POSTGRES_USER=circleci
          - POSTGRES_DB={{cookiecutter.project_name}}_test
          - POSTGRES_HOST_AUTH_METHOD=trust
      - image: redis

    steps:
      - checkout

      - run:
          name: Checking system dependencies
          command: make doctor

      - type: cache-restore
        key: poetry-{% raw %}{{ checksum "poetry.lock" }}{% endraw %}

      - run:
          name: Installing project dependencies
          command: make install

      - type: cache-save
        key: poetry-{% raw %}{{ checksum "poetry.lock" }}{% endraw %}
        paths:
          - .venv

      - run:
          name: Checking backend code
          command: make check-backend

      - run:
          name: Running backend tests
          command: make test-backend && sudo pip install coveralls && coveralls

      - run:
          name: Running frontend tests
          command: make test-frontend

      - run:
          name: Running system tests
          command: make build data test-system
          environment:
            DJANGO_SETTINGS_MODULE: config.settings.staging
            HEROKU_APP_NAME: {{cookiecutter.project_name}}-staging
            SECRET_KEY: staging

      - store_artifacts:
          path: htmlcov
