version: 2

jobs:
  build:
    working_directory: ~/{{cookiecutter.project_name}}

    docker:
      - image: circleci/python:3.7.5-stretch-node-browsers
        environment:
          DATABASE_URL: postgres://circleci:@127.0.0.1:5432/{{cookiecutter.project_name}}_test
          REDIS_URL: redis://127.0.0.1:6379/0
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          - POSTGRES_USER=circleci
          - POSTGRES_DB={{cookiecutter.project_name}}_test
      - image: redis

    steps:
      - checkout

      - run:
          name: Checking System Dependencies
          command: make doctor

      - type: cache-restore
        key: poetry-{% raw %}{{ checksum "poetry.lock" }}{% endraw %}

      - run:
          name: Installing Project Dependencies
          command: make install

      - type: cache-save
        key: poetry-{% raw %}{{ checksum "poetry.lock" }}{% endraw %}
        paths:
          - .venv

      - run:
          name: Checking Backend Code
          command: make check-backend

      - run:
          name: Running Backend Tests
          command: make test-backend

      - run:
          name: Running Frontend Tests
          command: make test-frontend

      - run:
          name: Running System Tests
          command: make build data test-system
          environment:
            DJANGO_SETTINGS_MODULE: config.settings.staging
            HEROKU_APP_NAME: {{cookiecutter.project_name}}-staging
            SECRET_KEY: staging
