version: 2

jobs:
  build:
    working_directory: ~/{{cookiecutter.project_name}}

    docker:
      - image: maketested/python-clojure:latest
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgres://circleci:@127.0.0.1:5432/{{cookiecutter.project_name}}_test
          RANDOM_SEED: 0
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          - POSTGRES_USER=circleci
          - POSTGRES_DB={{cookiecutter.project_name}}_test

    steps:
      - checkout

      - run:
          name: Checking system dependencies
          command: make doctor

      - type: cache-restore
        key: pipenv-{% raw %}{{ checksum "Pipfile.lock" }}{% endraw %}

      - run:
          name: Installing project dependencies
          command: make install

      - type: cache-save
        key: pipenv-{% raw %}{{ checksum "Pipfile.lock" }}{% endraw %}
        paths:
          - .venv

      - run:
          name: Checking backend code
          command: make check-backend

      - run:
          name: Running backend tests
          command: make test-backend

      - run:
          name: Running frontend tests
          command: make test-frontend

      - run:
          name: Running end-to-end tests
          command: make build data test-system
          environment:
            DJANGO_SETTINGS_MODULE: config.settings.staging
            HEROKU_APP_NAME: {{cookiecutter.project_name}}-staging
            SECRET_KEY: staging
