[tool.poetry]

name = "{{ cookiecutter.project_name }}"
version = "0.0"
description = ""
authors = ["{{ cookiecutter.full_name }} <you@yourdomain.com>"]

[tool.poetry.dependencies]

python = "^3.8"

# Django
django = "^3.0"
django-allauth = "*"
django-cors-headers = "*"
django-grappelli = "*"
django-memoize = "*"

# API
djangorestframework = "^3.7"
drf-nested-routers = "*"
drf-yasg = "*"

# Storage
dj-database-url = "=0.4.2"
psycopg2-binary = "^2.6"
django-redis-cache = "*"

# Utilities
faker = "*"
minilog = "^1.4"

# Deployment
whitenoise = "^5.0.1"
gunicorn = "^20.0.4"

[tool.poetry.dev-dependencies]

# Formatting
isort = "=4.3.21"
black = "=19.10b0"

# Linters
pylint = "^2.4.3"
mypy = "^0.761"

# Testing
pytest = "^5.3.2"
pytest-django = "*"
pytest-describe = "*"
pytest-expecter = "^2.0"
pytest-randomly = "*"
pytest-cov = "^2.8.0"
freezegun = "*"
coverage = "^5.0"
coveragespace = "^3.1.1"

# Tooling
django-livereload-server = "*"
honcho = "*"
splinter = "*"
fire = "*"
sniffer = "*"
pync = { version = "*", platform = "darwin" }
MacFSEvents = { version = "*", platform = "darwin" }

[tool.black]

target-version = ['py37']
skip-string-normalization = true
