web: bin/post_compile > /dev/null && gunicorn config.wsgi --bind=127.0.0.1:8001
# web: bin/post_compile > /dev/null && daphne config.asgi:application --port 8001
test: pytest tests/system -c tests/system/pytest.ini
